// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtUJ3eMhvJE10d1z6kBaYw006bfQzigoo',
    appId: '1:290741108396:web:a149ecbf38161a49e32909',
    messagingSenderId: '290741108396',
    projectId: 'uas-project-cd5fe',
    authDomain: 'uas-project-cd5fe.firebaseapp.com',
    storageBucket: 'uas-project-cd5fe.firebasestorage.app',
    measurementId: 'G-T4ELXPF2WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMqUFnmbOGD5wxRF0MEiCCfbRXqTSVnJU',
    appId: '1:290741108396:android:f7bffe05d9b8e01ee32909',
    messagingSenderId: '290741108396',
    projectId: 'uas-project-cd5fe',
    storageBucket: 'uas-project-cd5fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtUJ3eMhvJE10d1z6kBaYw006bfQzigoo',
    appId: '1:290741108396:web:f46a1a85a2db1d4be32909',
    messagingSenderId: '290741108396',
    projectId: 'uas-project-cd5fe',
    authDomain: 'uas-project-cd5fe.firebaseapp.com',
    storageBucket: 'uas-project-cd5fe.firebasestorage.app',
    measurementId: 'G-8009K8BW3C',
  );
}
